# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: train_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'train_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13train_service.proto\x12\x05train\"\x07\n\x05\x45mpty\"\x1b\n\tModelList\x12\x0e\n\x06models\x18\x01 \x03(\t\"\x8e\x01\n\x0cTrainRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\x37\n\nparameters\x18\x02 \x03(\x0b\x32#.train.TrainRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"2\n\rTrainResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x0ePredictRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"%\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x03(\x02\" \n\x0cModelRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\" \n\rModelResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xf6\x01\n\x0cTrainService\x12\x37\n\nTrainModel\x12\x13.train.TrainRequest\x1a\x14.train.TrainResponse\x12=\n\x0cPredictModel\x12\x15.train.PredictRequest\x1a\x16.train.PredictResponse\x12\x34\n\x12GetAvailableModels\x12\x0c.train.Empty\x1a\x10.train.ModelList\x12\x38\n\x0b\x44\x65leteModel\x12\x13.train.ModelRequest\x1a\x14.train.ModelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'train_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAINREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_TRAINREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_MODELLIST']._serialized_start=39
  _globals['_MODELLIST']._serialized_end=66
  _globals['_TRAINREQUEST']._serialized_start=69
  _globals['_TRAINREQUEST']._serialized_end=211
  _globals['_TRAINREQUEST_PARAMETERSENTRY']._serialized_start=162
  _globals['_TRAINREQUEST_PARAMETERSENTRY']._serialized_end=211
  _globals['_TRAINRESPONSE']._serialized_start=213
  _globals['_TRAINRESPONSE']._serialized_end=263
  _globals['_PREDICTREQUEST']._serialized_start=265
  _globals['_PREDICTREQUEST']._serialized_end=313
  _globals['_PREDICTRESPONSE']._serialized_start=315
  _globals['_PREDICTRESPONSE']._serialized_end=352
  _globals['_MODELREQUEST']._serialized_start=354
  _globals['_MODELREQUEST']._serialized_end=386
  _globals['_MODELRESPONSE']._serialized_start=388
  _globals['_MODELRESPONSE']._serialized_end=420
  _globals['_TRAINSERVICE']._serialized_start=423
  _globals['_TRAINSERVICE']._serialized_end=669
# @@protoc_insertion_point(module_scope)
