name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      minio:
        image: minio/minio
        ports:
          - 9000:9000
          - 9001:9001
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        options: >
          --entrypoint ""
        args:
          - server
          - /data
          - --console-address
          - ":9001"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment
      run: |
        echo "S3_ENDPOINT_URL=http://localhost:9000" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY_ID=minioadmin" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=minioadmin" >> $GITHUB_ENV

    - name: Pull DVC data
      run: dvc pull
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_ENDPOINT_URL: http://localhost:9000

    - name: Run tests
      run: |
        pytest tests/

  dvc-push:
    runs-on: ubuntu-latest
    needs: test

    services:
      minio:
        image: minio/minio
        ports:
          - 9000:9000
          - 9001:9001
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        options: >
          --entrypoint ""
        args:
          - server
          - /data
          - --console-address
          - ":9001"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install DVC and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc s3fs

    - name: Configure DVC remote
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
      run: |
        dvc remote modify minio_remote access_key_id $AWS_ACCESS_KEY_ID
        dvc remote modify minio_remote secret_access_key $AWS_SECRET_ACCESS_KEY
        dvc remote modify minio_remote endpointurl $S3_ENDPOINT_URL
        dvc push
