name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Remove existing MinIO container
      run: docker rm -f minio || true

    - name: Start MinIO
      run: |
        docker run -d --name minio \
          -p 9000:9000 -p 9001:9001 \
          -e "MINIO_ROOT_USER=minioadmin" \
          -e "MINIO_ROOT_PASSWORD=minioadmin" \
          minio/minio server /data --console-address ":9001"

    - name: Wait for MinIO to start
      run: sleep 10

    - name: Check MinIO readiness
      run: |
        for i in {1..10}; do
          curl -s http://localhost:9000/minio/health/ready && break || sleep 2
        done

    - name: Create bucket in MinIO
      run: |
        pip install boto3
        python - <<EOF
        import boto3
        from botocore.exceptions import ClientError

        s3 = boto3.client(
            's3',
            endpoint_url='http://localhost:9000',
            aws_access_key_id='minioadmin',
            aws_secret_access_key='minioadmin'
        )
        try:
            s3.head_bucket(Bucket='test-bucket')
            print("Bucket 'test-bucket' already exists.")
        except ClientError:
            s3.create_bucket(Bucket='test-bucket')
            print("Bucket 'test-bucket' created.")
        EOF

    - name: Set up environment
      run: |
        echo "S3_ENDPOINT_URL=http://localhost:9000" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY_ID=minioadmin" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=minioadmin" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt dvc s3fs boto3

    - name: Reproduce DVC pipeline
      run: dvc repro
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}

    - name: Pull DVC data
      run: dvc pull
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}

    - name: Run tests
      run: pytest tests/

  dvc-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove existing MinIO container
      run: docker rm -f minio || true

    - name: Start MinIO
      run: |
        docker run -d --name minio \
          -p 9000:9000 -p 9001:9001 \
          -e "MINIO_ROOT_USER=minioadmin" \
          -e "MINIO_ROOT_PASSWORD=minioadmin" \
          minio/minio server /data --console-address ":9001"

    - name: Wait for MinIO to start
      run: sleep 10

    - name: Check MinIO readiness
      run: |
        for i in {1..10}; do
          curl -s http://localhost:9000/minio/health/ready && break || sleep 2
        done

    - name: Create bucket in MinIO
      run: |
        pip install boto3
        python - <<EOF
        import boto3
        from botocore.exceptions import ClientError

        s3 = boto3.client(
            's3',
            endpoint_url='http://localhost:9000',
            aws_access_key_id='minioadmin',
            aws_secret_access_key='minioadmin'
        )
        try:
            s3.head_bucket(Bucket='test-bucket')
            print("Bucket 'test-bucket' already exists.")
        except ClientError:
            s3.create_bucket(Bucket='test-bucket')
            print("Bucket 'test-bucket' created.")
        EOF

    - name: Install DVC and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc s3fs boto3

    - name: Add and commit DVC outputs
      run: |
        dvc add data/test_data.txt models/model.pkl
        git add data/test_data.txt.dvc models/model.pkl.dvc
        git commit -m "Track DVC outputs"

    - name: Configure DVC remote and push
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
      run: |
        dvc remote modify minio_remote access_key_id $AWS_ACCESS_KEY_ID
        dvc remote modify minio_remote secret_access_key $AWS_SECRET_ACCESS_KEY
        dvc remote modify minio_remote endpointurl $S3_ENDPOINT_URL
        dvc push
